# Generated by Django 5.2.4 on 2025-07-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
    ]
