# Generated by Django 5.2.4 on 2025-07-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='college',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='course',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='year_of_study',
            new_name='graduation_year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Educational background', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='experience',
            field=models.TextField(blank=True, help_text='Work experience details', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio website URL', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True, help_text='Personal/academic projects', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF)', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills (e.g., Python, JavaScript, React)', null=True),
        ),
    ]
