# Generated by Django 5.2.4 on 2025-12-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_college_studentprofile_college_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
