# render.yaml
services:
  - type: web
    name: smart-job-portal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn jobportal.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jobportal.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    staticPublishPath: staticfiles
